### ISSUE TITLE
Cannot update composer anymore for v3.3.0?

### ISSUE THREAD

**Issue by Lambik** [Antidot-be/bpost-api-library#1]
Hi,

On my dev machine, I have installed this package at v3.3.0 some months ago. Now when I want to composer install on my server, with the composer.json constraint "antidot-be/bpost-api-library": "^3.3.0", I get the following error:

  Your requirements could not be resolved to an installable set of packages.
    Problem 1
      - The requested package antidot-be/bpost-api-library ^3.3.0 exists as antidot-be/bpost-api-library[3.0.0, 3.0.1, 3.0
  .2, 3.0.x-dev, dev-master, dev-track-and-trace] but these are rejected by your constraint.

Is this related to the change you made 4 days ago for version 3.4.0? What can I do to get the 3.3.0+ version on my server?

Best regards!

**Comment by rpommier-antidot** [comment]
Hi,
Indeed, some tags are gone (I deleted and recreated the repository to mark it as forked from tijsverkoyen/bpost), sorry for the collateral damage.
This morning, I recreated releases 3.3.0 and 3.4.0.
Can you retry and tell me if that's fixed ?

Thanks.

**Comment by Lambik** [comment]
Hi,

Thanks for the fix, it does work again :-)
I did think it strange that all commits seemed to be on one day, while referencing the past...

Glad you got it working again! Best regards!
