### ISSUE TITLE
PHP 7.2 compatibility issue

### ISSUE THREAD

**Issue by stijnster** [Antidot-be/bpost-api-library#11]
Hi,

we are preparing an upgrade to PHP 7.2, but when we run our unit tests we get an instant PHP Fatal Error on the bpost-api-library.

```
PHP Fatal error:  Declaration of Bpost\BpostApiClient\Bpost\Order\Box\AtHome::createFromXML(SimpleXMLElement $xml) must be compatible with Bpost\BpostApiClient\Bpost\Order\Box\National::createFromXML(SimpleXMLElement $nationalXml, ?Bpost\BpostApiClient\Bpost\Order\Box\National $self = NULL) in  [...]/antidot-be/bpost-api-library/src/Bpost/Order/Box/AtHome.php on line 18
```

There is a mismatch in method signatures, and starting from php 7.2, this throws a fatal error.

After some inspection inside the library, I think the issue can easily resolved by changes this line;

```
antidot-be/bpost-api-library/src/Bpost/Order/Box/AtHome.php
```
From;
```
public static function createFromXML(\SimpleXMLElement $xml)
```
To;
```
public static function createFromXML(\SimpleXMLElement $xml, $self = null)
```

~~I would love to make a patch that you can pull into the repo, but the problem is that the current version of `phpunit`, used in the library for testing, is also incompatible with php 7.2~~

~~Upgrading the `phpunit` unit would resolve the issue, but would also require the unit tests to be modified.~~

**Comment by stijnster** [comment]
As you can read in the pull request, I was able to make the required change and make unit tests pass both in the library (up to php 7.1) and locally in my application (php 7.2).

It would be great if you can merge this pull request!

Thanks

**Comment by pinkminds** [comment]
Thx @stijnster! Would be great if this could be pulled into the repo so we can upgrade our PHP version.

**Comment by stijnster** [comment]
Thanks for merging, this issue can therefor be closed!
