### ISSUE TITLE
Insurance doesn't fully work?

### ISSUE THREAD

**Issue by Lambik** [Antidot-be/bpost-api-library#3]
Hi,

I've created a package that is insured, and it's been sent off correctly to bpost.

When I now poll the bpost api (using bpost->fetchOrder), it claims the box has the option "insured".
However, this fails (Bpost\Order\Box\National.php:241):

```
                $className = '\\Bpost\\BpostApiClient\\Bpost\\Order\\Box\\Option\\' . ucfirst($optionData->getName());
                if (!method_exists($className, 'createFromXML')) {
                    throw new BpostXmlInvalidItemException();
                }
```

This throws the exception that $optionData->getName() returns 'insured', and there is no such class. I do see a class called 'Insurance'. Should this one be renamed?

**Comment by kouinkouin** [comment]
Hi,

Indeed, the "Insurance" class treats the "Insured" option, but the mapping seems wrong.
We can check with others options:
- cod (class CashOnDelivery)
- signed (class Signature)

I will not work on the library in the next days.
Without check the code, we could create a mapping `$optionData->getName() => $className` with a switch.
Don't hesitate to make a pull request if you have time to fix it :) .

**Comment by webcraft** [comment]
I get a similar error with AutomaticSecondPresentation.
The classname does match in this case, but there is no createFromXML() method on this class. I think other option classes, like Insurance, will have the same problem.
So I think what's needed is implementing the createFromXML() methods on all the option classes, right?
