### ISSUE TITLE
Postalcode is limited to 8 characters instead of suggested 40

### ISSUE THREAD

**Issue by stijnster** [Antidot-be/bpost-api-library#8]
Hi There,

I'm posting this issue here, as I get the feeling that this is now the main repository for this library.

Although the error messages below refer to the original package, I think the issue still stands as the line of code has not changed in your repository.

Could you please check and verify that the maximum amount of characters for postalcodes is 8, instead of the 40 that you check on in your class;

`tijsverkoyen/bpost/Bpost/Order/Address.php`

```php 
public function setPostalCode($postalCode)
{
        $length = 40;
        if (mb_strlen($postalCode) > $length) {
            throw new Exception(sprintf('Invalid length, maximum is %1$s.', $length));
        }
        $this->postalCode = $postalCode;
    }
```

We received this error when we passed in a value, longer then 8.

>TijsVerkoyen\Bpost\Exception: Uncaught exception 'TijsVerkoyen\Bpost\Exception' with message 'Error in request: cvc-maxLength-valid: Value '123456789012' with length = '12' is not facet-valid with respect to maxLength '8' for type 'PostalCodeType'.

Thanks for your work on this!

**Comment by pinkminds** [comment]
Any news on this one? We are running into the same issue.

**Comment by kouinkouin** [comment]
On the doc http://bpost.freshdesk.com/helpdesk/attachments/4040238131 at the point B 3.3.1, the postal code is limited to 40 characters.
It's strange the doc/spec are not aligned with API. Or maybe I'm wrong somewhere ?

(document available from http://bpost.freshdesk.com/support/solutions/articles/4000037653-where-can-i-find-the-bpack-integration-manual-examples-and-xsd-s-)

**Comment by pinkminds** [comment]
Indeed, seems like the documentation is not consistent with the API...

**Comment by stijnster** [comment]
Mmmm... when I look at the PDF manual "bpack integration manual v3.3.13)" on the same page that @kouinkouin suggested, under "B.2.2.1" a list of fields and their max length values are specified. And the max length for a Postal Code is indeed 8 characters, not 40.

Just for your information; earlier we've had a similar issue with the Company field (that has nog length restrictions in the library); we received an error on a Company name that was 42 characters. The error stated that it should be no longer the 40 characters. Which, again, is consistent with section B.2.2.1).

It seems that only part of the documentation is up to date then. API integration should follow section 3, but we're receiving errors consistent with section 2.

I've sent an e-mail with the request to update the documentation.


Keep you posted!
